services:
  - type: web
    name: quiz-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://sushant:sushant@quizapp.k5qcg.mongodb.net/?retryWrites=true&w=majority&appName=QuizApp
      - key: JWT_SECRET
        value: itsasecret
      - key: PORT
        value: 3030
